ENH: Layout Slider using layout classes
psychopy/psychopy pull request #4401
Opened 2021-11-30 15:48 UTC by TEParsons

Fixes problems with laying out labels with vertical sliders - as we no longer need to guess and offset the label width, we can instead just use TextBox2 components with an anchor property

2021-12-06 15:07 UTC, peircej commented
Task linked: [CU-1n012p5 Make Slider size/pos settable with layout classes so that Form lays out correctly](https://app.clickup.com/t/1n012p5)

2021-12-09 21:52 UTC, mdcutone requested changes
Bit of déjà vu for some of the commits here with PR #4407

2021-12-09 21:52 UTC, mdcutone commented on psychopy/layout.py
> +                value[value == None] = getattr(win, units)[value == None]
Wasn't this changed in another PR? Might cause a merge conflict.

2021-12-10 10:02 UTC, TEParsons commented
> Bit of déjà vu for some of the commits here with PR #4407

Yep, 4407 is based on this branch - couldn't fix Forms until Slider was working.

2021-12-10 15:42 UTC, merged