DOCS: Update Simplified Chinese translations
psychopy/psychopy pull request #5969
Opened 2023-10-24 18:13 UTC by ice-yu

2023-10-25 03:54 UTC, shun2wang requested changes

2023-10-25 03:54 UTC, shun2wang commented on psychopy/app/locale/zh_CN/LC_MESSAGE/messages.po
> +msgstr "系统定位"
```suggestion
msgstr "系统区域"
```
system locale 即系统区域，是和语言、货币符号、时间格式等绑定。

2023-10-25 03:54 UTC, shun2wang commented on psychopy/app/locale/zh_CN/LC_MESSAGE/messages.po
> +msgstr "逗号隔开的按键（需输入引号），例：’q’,’right’,’space’,’left’"
```suggestion
msgstr "逗号隔开的按键（需输入引号），例：'q','right','space','left'"
```
这里需要使用英文单引号，因为与python语句绑定。

2023-10-25 13:42 UTC, shun2wang approved these changes

2023-11-01 23:59 UTC, shun2wang approved these changes

2023-11-02 12:57 UTC, shun2wang commented
@peircej this could be merged.

2023-11-29 19:34 UTC, closed without merging

2023-11-30 01:15 UTC, shun2wang commented
Hi @ice-yu Why you closed it? can you make a new PR or reopen it again:-)

2023-11-30 01:18 UTC, ice-yu commented
Hi,

Just opened a PR!

Shun Wang ***@***.***> 于2023年11月29日周三 20:15写道：

> Hi @ice-yu <https://github.com/ice-yu> Why you closed it? can you make a
> new PR or reopen it again:-)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/psychopy/psychopy/pull/5969#issuecomment-1832949574>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATWRAF35GRPDHPXL3BKLGKLYG7M3NAVCNFSM6AAAAAA6ODPRTKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMZSHE2DSNJXGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>