ENH: Device selection for multiple sounds (ptb library)
psychopy/psychopy pull request #6342
Opened 2024-03-27 13:35 UTC by janna-stb

I implemented the option to select different output devices for multiple streams using the ptb library. The ptb library already had this functionality, but until now the psychopy code did not pass the device ID correctly. As a result, the sound was not output on the selected device. This will now work correctly and the sound will be played through the corresponding device/output for multiple simultaneous sounds on different devices.

2024-05-31 13:33 UTC, mdcutone commented on psychopy/sound/_base.py
> +    def setSound(self, value, device, secs=0.5, octave=4, hamming=True, log=True):
I'm concerned adding `device` here may break existing code that doesn't set that value. Possible solution would be to append `device` to the end of the keyword arguments and allow it to take None.

2024-06-21 13:37 UTC, peircej requested changes

2024-06-21 13:37 UTC, peircej commented on psychopy/sound/backend_ptb.py
> -        elif sys.platform == 'win32' and len(self):
@janna-stb is this really not needed any longer, or did you just remove it while making changes to `getStreamLabel` ?

2024-09-03 13:58 UTC, zeyus commented
I've just had to implement dual audio output (one for stimuli and another for audio triggers), but I have managed to do this with the current implementation (with ptb on windows 11) using:
```python
sound1 = Sound("./test.wav", speaker="Headphhones...")
sound2 = Sound("./test2.wav", speaker="Speaker...")

# ...
sound1.play()
sound2.play()
```

and you could update the speaker by using `sound1.speaker = DeviceManager.getDevice("Another device")`

Just curious about the difference.

2024-10-31 15:11 UTC, TEParsons commented
We're currently making changes with multi-speaker setups in mind (see #6953) so this will no longer be needed - as the ptb stream will be an attribute of the speaker rather than of the sound, the device index will be set by pointing the sound object to the correct speaker object. Thanks for contributing still though! I'll make sure the core changes from here are included.

2024-10-31 15:11 UTC, closed without merging